# TODO: integrate other intermine images? -> https://hub.docker.com/u/intermine

services:
  # TODO: db backup (volumes)
  db:
    image: postgres:15
    # restart: unless-stopped
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./pg_upd.conf:/etc/postgresql.conf
    environment:
      # TODO: define secrets using GH secrets: use ssh-action to modify properties and docker secrets files?
      POSTGRES_MULTIPLE_DATABASES: mdrmine,items-mdrmine,userprofile-mdrmine
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_INITDB_ARGS: '--encoding=SQL_ASCII --lc-collate=C --lc-ctype=C'
    command: -c config_file=/etc/postgresql.conf
    ports:
      - "5433:5432"
    secrets:
      - postgres_user
      - postgres_password
  tomcat:
    build:
      context: .
      secrets:
        - tomcat_user
        - tomcat_password
      dockerfile: ./Dockerfiles/tomcat/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - webapps:/usr/local/tomcat/webapps
  bluegenes:
    # build:
      # context: ../bluegenes
      # dockerfile: ../bluegenes/Dockerfile
    image: intermine/bluegenes:1.4.5-dx
    restart: unless-stopped
    volumes:
      - type: bind
        source: ~/.intermine/tools
        target: /tools
        bind:
          create_host_path: true
    env_file: ~/.intermine/bluegenes.env
    ports:
      - "8090:8090" # this is 8090:8090 because of the config in bluegenes.env
  solr:
    image: solr:latest
    restart: unless-stopped
    volumes:
      - solr_data:/var/solr
    entrypoint:
      - bash
      - "-c"
      - "mkdir -p /var/solr/data; precreate-core mdrmine-search; precreate-core mdrmine-autocomplete; exec solr -f -Dvelocity.solr.resource.loader.enabled=true"
    ports:
      - "8983:8983"
  mdrmine:
    build:
      args:
        SOURCES: $SOURCES
        LOCAL: $LOCAL
        EMPTY: $EMPTY
        HOSTNAME: db  # this needs to match Postgres service name
      context: .
      dockerfile: ./Dockerfiles/main/Dockerfile
      target: mdrmine_build
    environment:
      SSH_AUTH_SOCK: /ssh-agent
    volumes:
      - webapps:/webapps
      - type: bind
        source: ~/.intermine
        target: /root/.intermine
        read_only: true
      - type: bind
        source: /home/ubuntu/data/
        target: /home/ubuntu/data/
      - type: bind
        source: ./sources_logs
        target: /mdrmine/sources_logs
      - type: bind
        source: $SSH_AUTH_SOCK
        target: /ssh-agent

# Note: change this a shared bind mount to keep the Tomcat default apps (Manager, etc.) https://stackoverflow.com/a/46111405/23455986
volumes:
  webapps:
  solr_data:

secrets:
  postgres_user:
    file: ./secrets/postgres_user
  postgres_password:
    file: ./secrets/postgres_password
  tomcat_user:
    file: ./secrets/tomcat_user
  tomcat_password:
    file: ./secrets/tomcat_password