#contains only classes that come from more than one source
#for each class contained every source for that class must be listed

# priority for fields declared in superclass are not overridden by different order in subclass
# e.g. identfier and organism always have priority as defined in BioEntity

# For example, to give interpro prioritiy over uniprot for the 'shortName' field of ProteinDomain:
#
# ProteinDomain.shortName = interpro, uniprot

# To give flybase priority over all other sources for Gene name:
#
# Gene.name = flybase, *
Study.primaryIdentifier = ctis, euctr, ctg, biolincc, *
Study.nctID = ctis, euctr, ctg, biolincc, *
Study.euctrID = ctis, euctr, ctg, biolincc, *
Study.displayTitle = ctis, ctg, euctr, biolincc, *
Study.publicTitle = ctis, ctg, euctr, biolincc, *
Study.scientificTitle = ctis, ctg, euctr, biolincc, *
Study.acronym = ctis, ctg, euctr, biolincc, *
Study.titleLang = ctis, ctg, euctr, biolincc, *
Study.description = ctis, ctg, biolincc, *
Study.planToShareIPD = ctis, ctg, euctr, biolincc, *
Study.dataSharingStatement = ctis, ctg, euctr, biolincc, *
Study.startDate = ctis, ctg, euctr, biolincc, *
Study.endDate = ctis, ctg, euctr, biolincc, *
Study.type = ctis, ctg, euctr, biolincc, *
Study.status = ctis, ctg, euctr, biolincc, *
Study.genderElig = ctis, ctg, euctr, biolincc, *
Study.plannedEnrolment = ctis, ctg, euctr, biolincc, *
Study.actualEnrolment = ctis, ctg, euctr, biolincc, *
Study.ageGroup = ctg, euctr, biolincc, ctis, *
Study.minAge = ctg, euctr, biolincc, ctis, *
Study.minAgeUnit = ctg, euctr, biolincc, ctis, *
Study.maxAge = ctg, euctr, biolincc, ctis, *
Study.maxAgeUnit = ctg, euctr, biolincc, ctis, *
Study.iec = ctis, ctg, euctr, biolincc, *
Study.interventionsDescription = ctis, ctg, euctr, biolincc, *
Study.primaryOutcome = ctis, ctg, euctr, biolincc, *
Study.secondaryOutcomes = ctis, ctg, euctr, biolincc, *
Study.hasResults = ctg, ctis, euctr, biolincc, *

StudyCondition = ctis, ctg, euctr, biolincc, *
StudyCountry = ctis, ctg, euctr, biolincc, *
StudyFeature = ctis, ctg, euctr, biolincc, *
StudyIdentifier.study = ctis, ctg, euctr, biolincc, *
StudySite = ctis, ctg, euctr, biolincc, *
Intervention = ctis, ctg, euctr, biolincc, *

RegistryResultsSummary = ctis, ctg, euctr, biolincc, *
Protocol = ctis, ctg, euctr, biolincc, *
StatisticalAnalysisPlan = ctis, ctg, euctr, biolincc, *
InformedConsentForm = ctis, ctg, euctr, biolincc, *
EthicsApprovalNotification = ctis, ctg, euctr, biolincc, *
IndividualParticipantData = ctis, ctg, euctr, biolincc, *
Biosample = biolincc, ctis, ctg, euctr, *

Organisation = ctis, ctg, euctr, biolincc, *
Person = ctis, ctg, euctr, biolincc, *
Relationship = ctis, ctg, euctr, biolincc, *

Country = ctis, ctg, euctr, biolincc, *
